num_workers: 16

task: denovo
top_pks: 100
pep_length: [0, 30]
charge: [0, 10]
add_mass: True

paths:
  train:
    - train-00001-of-00002-fb1cb1b5c4a4ef4f.parquet
    - train-00000-of-00002-ca1fbc3de7c99259.parquet
  val: 
    - validation-00000-of-00001-b84568f5bf3ba95d.parquet
  test: 
    - test-00000-of-00001-15be7bb3864037e7.parquet

denovo_tf:
  # DeNovoTeacherForcing specific hparams
  conf_threshold: 0
  # Training hparams
  batch_size: 100
  ref_batch_size: 100
  blr: 5.0e-5
  weight_decay: 0
  epochs: 15
  subset: 0
  num_workers: 16

denovo_random:
  # DeNovoTeacherRandom specific hparams
  conf_threshold: 0
  # Training hparams
  batch_size: 100
  ref_batch_size: 100
  blr: 1.0e-4
  weight_decay: 0
  epochs: 30
  subset: 0
  num_workers: 16
