num_workers: 16

dataset_name: ninespecies_hf
task: denovo
top_pks: 100 # this doesn't work
pep_length: [0, 30]
charge: [0, 10]
add_mass: True

paths:
  train:
    - train-00001-of-00002-fb1cb1b5c4a4ef4f.parquet
    - train-00000-of-00002-ca1fbc3de7c99259.parquet
  val: 
    - validation-00000-of-00001-b84568f5bf3ba95d.parquet
  test: 
    - test-00000-of-00001-15be7bb3864037e7.parquet

val_species: saccharomyces_cerevisiae

denovo_tf:
  # DeNovoTeacherForcing specific hparams
  conf_threshold: 0
  # Training hparams
  blr: 1.0e-4
  lr_warmup: 0
  lr_start: 1.0e-7
  lr_end: 2.0e-4
  lr_warmup_steps: 20000
  lr_decay: 0
  lr_decay_start_step: 5000
  lr_decay_end_step: 25000
  lr_decay_rate: 0.9999
  batch_size: 100
  ref_batch_size: 100
  label_smoothing: 0
  weight_decay: 0
  epochs: 40
  subset: 0
  num_workers: 16
  decoder_dropout: 0.25

denovo_random:
  # DeNovoTeacherRandom specific hparams
  conf_threshold: 0
  # Training hparams
  blr: 5.0e-5
  lr_warmup: 0
  lr_start: 1.0e-7
  lr_end: 2.0e-4
  lr_warmup_steps: 20000
  batch_size: 100
  ref_batch_size: 100
  weight_decay: 0
  epochs: 30
  subset: 0
  num_workers: 16
  decoder_dropout: 0
