num_workers: 16

dataset_name: massivekb
task: denovo
max_peaks: 100
pep_length: [0, 30]
charge: [0, 10]
add_mass: True


denovo_tf:
  # DeNovoTeacherForcing specific hparams
  conf_threshold: 0
  # Training hparams
  blr: 1.0e-4
  lr_warmup: 1
  lr_start: 1.0e-7
  lr_end: 2.0e-4
  lr_warmup_steps: 20000
  lr_decay: 0
  lr_decay_start_step: 5000
  lr_decay_end_step: 25000
  lr_decay_rate: 0.9999
  batch_size: 100
  ref_batch_size: 100
  label_smoothing: 0
  weight_decay: 0
  epochs: 30
  subset: 0
  num_workers: 16

denovo_random:
  # DeNovoTeacherRandom specific hparams
  conf_threshold: 0
  # Training hparams
  batch_size: 100
  ref_batch_size: 100
  blr: 1.0e-4
  weight_decay: 0
  epochs: 30
  subset: 0
  num_workers: 16
