# update your env with 'conda env update --file environment.yml --prune'
# or 'mamba env update --file environment.yml --prune'
name: Pairwise
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - pytorch-lightning
  - pandas
  - scipy
  - numpy
  - pip
  - pip:
      - matplotlib
      - wandb
      - path
      - pathlib
      - jiwer
      - pylance==0.10.10
      - datasets
