# create a conda env with 'conda env create -f environment.yml'
name: MS2transformers
channels:
  - conda-forge
dependencies:
  - python=3.9 # 3.10 bugs out some dependencies
  - scikit-learn
  - pytorch-lightning
  - pytorch=1.13
  - pandas
  - scipy
  - pip
  - pip:
    - matplotlib
    - wandb