
# Must set these options for the HF dataset. There are no global arguments for them.
# See utils.py:get_ninespecies_HF_data_module
#
# apis_mellifera 196222
# homo_sapiens 44925
# bacillus_subtilis 1359692
# candidatus_endoloripes 82335
# methanosarcina_mazei 264460
# mus_musculus 26074
# saccharomyces_cerevisiae 589091
# solanum_lycopersicum 181538
# vigna_mungo 1103314
task: denovo
dataset_name: ninespecies_hf
val_species: saccharomyces_cerevisiae
top_peaks: 150 # independent of max_peaks
pep_length: [0, 100]
charge: [0, 10]
buffer_size: 10000

denovo_tf:
  # DeNovoTeacherForcing specific hparams
  conf_threshold: 0
  # Training hparams
  anneal_lr: True
  anneal_per_step: True
  lr_start: 1.0e-7
  blr: 2.0e-4
  lr_end: 1.0e-4
  warmup_duration: 20000
  decay_delay: 0
  decay_duration: -1
  batch_size: 100
  ref_batch_size: 100
  label_smoothing: 0
  weight_decay: 0
  epochs: 50 # 50
  subset: 0
  decoder_dropout: 0.25
  decoder_use_cls: False

