data_root_dir: /proj/bedrock/datasets/instanovo_data_subset/
output_dir: /proj/bedrock/checkpoints/checkpoint
log_dir: /proj/bedrock/logs/log
wandb_project: debug
wandb_entity: kall
log_wandb: 1
num_workers: 16
matmul_precision: high
precision: 32-true
### Models
encoder_model: encoder_base_arch
###
anneal_lr: 0
min_lr: 0
warmup_epochs: 0
### Training hyperparameters
batch_size: 100
blr: 4e-5
weight_decay: 0
epochs: 30
# use_mass: 1
# use_charge: 1
max_peaks: 300
# Task
pretrain: 0
pretraining_task: trinary_mz
# De novo
downstream_task: denovo
decoder_model: decoder_greedy_base
downstream_root_dir: /proj/bedrock/datasets/9_species_xy