data_root_dir: /proj/bedrock/datasets/foundational_dataset/combined/
output_dir: /proj/bedrock/checkpoints/checkpoint
log_dir: /proj/bedrock/logs/log
wandb_project: combined-Dino
wandb_entity: kall
log_wandb: 1
num_workers: 16
matmul_precision: high
precision: 32-true

###### TODO: FIX THESE WARMUP HPARAMS
anneal_lr: 0
warmup_epochs: 0
### Training hyperparameters
max_peaks: 1000

# Tasks
encoder_model: dc_encoder_larger
cls_token: 1
pretrain_config: configs/pretrain/dc.yaml
pretrain: 1
pretraining_task: dino
mask_ratio: 0.75

# De novo
decoder_model: dc_decoder_base
downstream_config: configs/downstream/dc.yaml
downstream_task: denovo_tf
downstream_root_dir: /proj/bedrock/datasets/9_species_xy