data_root_dir: /Users/alfred/Documents/Datasets/instanovo_data_subset
wandb_project: debug
wandb_entity: kall
### Models
encoder_model: encoder_base_arch
### Training hyperparameters
lr: 4e-5
epochs: 5