data_root_dir: /proj/bedrock/datasets/foundational_dataset/combined
output_dir: /proj/bedrock/checkpoints/checkpoint
log_dir: /proj/bedrock/logs/log
wandb_project: debug # ProteomeTools | {choose your exp.}
wandb_entity: joellapin # kall | joellapin
log_wandb: 1
num_workers: 16
matmul_precision: high
precision: 32-true

# Checkpointing
save_top_k: 0
save_last: 0
every_n_epochs: 0
every_n_train_steps: 10000 # utils.py:329

# Models
encoder_model: encoder_base_arch # encoder_base_arch | dc_encoder_base | encoder_pairwise
decoder_model: dc_decoder_base # decoder_greedy_base | dc_decoder_base

#### Training hyperparameters
batch_size: 100
max_peaks: 100
seed: 0

# Tasks
pretrain: 0
encoder_weights:
pretrain_config: configs/pretrain/joel.yaml
pretraining_task: trinary_mz
trinary_type: 'mz'
mask_ratio: 0.75
# De novo
downstream_config: configs/downstream/joel.yaml
downstream_task: denovo_tf # none | denovo_tf
downstream_root_dir: /proj/bedrock/datasets/9_species_xy
limit_train_batches: 1.0
