data_root_dir: /proj/bedrock/datasets/bacteria_PXD010000__PXD010613/no_labels/
output_dir: /proj/bedrock/checkpoints/checkpoint
log_dir: /proj/bedrock/logs/log
wandb_project: bacterial # ProteomeTools | {choose your exp.}
wandb_entity: kall # kall | joellapin
log_wandb: 1
num_workers: 8
matmul_precision: high
precision: 32-true

# Checkpointing
save_top_k: 1
save_last: 0
every_n_epochs: 1
every_n_train_steps: # utils.py:329
remove_ckpt: 1

# Models
encoder_model: encoder_pairwise # encoder_base_arch | dc_encoder_base | encoder_pairwise
decoder_model: dc_decoder_base # decoder_greedy_base | dc_decoder_base

#### Training hyperparameters
batch_size: 100
max_peaks: 100
seed: 0

# Tasks
pretrain: 0
encoder_weights:
pretrain_config: configs/pretrain/joel.yaml # joel.yaml | dc.yaml
pretraining_task: trinary_mz # trinary_mz | dino | masked_ae
trinary_type: 'mz'
mask_ratio: 0.75
# De novo
downstream_config: configs/downstream/joel.yaml
downstream_task: denovo_tf # none | denovo_tf
downstream_root_dir: /proj/bedrock/datasets/9_species_V1
downstream_weights:
limit_train_batches: 1.0
limit_val_batches: 200
validate_every_n_epochs: 1
