data_root_dir: /proj/bedrock/datasets/InstaNovo_SPLITS_full
output_dir: /proj/bedrock/checkpoints/checkpoint
log_dir: /proj/bedrock/logs/log
wandb_project: ProteomeTools
wandb_entity: kall
log_wandb: 1
num_workers: 16
matmul_precision: high
precision: 32-true
# Models
encoder_model: dc_encoder_base #encoder_base_arch # dc_encoder_base

#### Training hyperparameters
batch_size: 100
max_peaks: 100
seed: 0

# Tasks
pretrain: 1
pretrain_config: configs/pretrain/joel.yaml
pretraining_task: trinary_mz
trinary_type: 'mz'
mask_ratio: 0.75
# De novo
downstream_config: configs/downstream/joel.yaml
downstream_task: none # denovo_tf
decoder_model: dc_decoder_jl # decoder_greedy_base | dc_decoder_base
downstream_root_dir: /proj/bedrock/datasets/9_species_xy


