trinary_mz:
  test: 123

  # Training hparams
  blr: 4.0e-5
  weight_decay: 1.0e-5
  epochs: 1
  subset: 0
  num_workers: 0

masked:
  # Masked trainer specific hparams
  predict_fourier: True
  mask_token_fourier: True
  learned_masked_token: True
  positional_encoding: True
  mz_to_int_ratio: 0.67
  
  # Training hparams
  blr: 4.0e-5
  weight_decay: 1.0e-5
  epochs: 1
  subset: 0
  num_workers: 0