seed: 10
max_peaks: 100
epochs: 5
steps_per_epoch: 10000
batch_size: 100
lr: 4e-5
tasks:
  - trinary_mz
  #- trinary_ab
  #- hidden_mz
  #- hidden_ab
  #- hidden_spectrum
  #- hidden_charge
  #- hidden_mass
  #- doctored_mz
  #- doctored_mz2
downstream:
  #- charge
    #- peplen
  - denovo_ar
load: False
loadpath: save/2023-09-27_06-24-36.363775/weights/
svwts: True
svfreq: 1800
log: True
debug: False
header: "Large model for both encoder and decoder"
