batch_size: 100
lr: 0.00005
pretrain_path:
epochs: 10
steps_per_epoch: 10000
train_encoder: True
encoder_start: 1000
save_weights: False
debug: False
# Loader options
loader:
  top_pks: 100
  pep_length: [0, 30]
  charge: [0, 10]
  add_mass: True
  paths:
    train:
      - /cmnfs/data/proteomics/foundational_model/ninespecies_xy/train-00001-of-00002-fb1cb1b5c4a4ef4f.parquet
      - /cmnfs/data/proteomics/foundational_model/ninespecies_xy/train-00000-of-00002-ca1fbc3de7c99259.parquet
    val: 
      - /cmnfs/data/proteomics/foundational_model/ninespecies_xy/validation-00000-of-00001-b84568f5bf3ba95d.parquet
    test: 
      - /cmnfs/data/proteomics/foundational_model/ninespecies_xy/test-00000-of-00001-15be7bb3864037e7.parquet
# Downstream task specific options
denovo_bl:
  head_dict:
    penult_units: 512
    drop_rate: 0
denovo_ar:
  head_dict:
    running_units: 512
    sequence_length: 30
    depth: 9
    d: 64
    h: 4
    ffn_multiplier: 1
    ce_units: 256
    use_charge: True
    use_energy: False
    use_mass: True
    norm_type: 'layer'
    prenorm: True
    preembed: True
    penultimate_units:
    pool: False
charge:
  head_dict:
    penult_units: 512
    spectrum_wise: True
peplen:
  head_dict:
    penult_units: 512
    spectrum_wise: True
